### PR TITLE
chore: Update copyright notice and do a great refactor

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by Wellinator** [comment]
Hey! Thx for collabing!
Please resolve the conflics with the most recent updates.
Please take a look that some notes and Todos have already been done! :D 
@wolfysdl

**Comment by Wolf3s** [comment]
> Hey! Thx for collabing! Please resolve the conflics with the most recent updates. Please take a look that some notes and Todos have already been done! :D @wolfysdl

Ok i will update but first i need to do some stuff first :)

**Comment by Wolf3s** [comment]
@Wellinator done

**Comment by Wellinator** [comment]
It are still no building ;(

**Comment by Wolf3s** [comment]
> It are still no building ;(

Weird :(

**Comment by Wellinator** [comment]
I could compile the engine but not the cube sample! Pls fix it

**Comment by Wolf3s** [comment]
> I could compile the engine but not the cube sample! Pls fix it

Ok aparently is more like lib stuff

**Comment by Wolf3s** [comment]
https://user-images.githubusercontent.com/75867486/173130022-b46465b5-7c9e-4e06-875d-c956378129eb.mp4

@Wellinator

**Comment by Wolf3s** [comment]
UPDATE 2022-06-29:
I finally found the problem, it looks like about the fread stuff. i tried to port fread(); to newlib declararion called open(); and it compiles good. probably i'll will change fread to fopen. Soon i will send a video showing off.

**Comment by Wellinator** [comment]
New changes will be migrated to TyraV2

**Comment by Wolf3s** [comment]
> New changes will be migrated to TyraV2

Just put my credits ok?

**Comment by Wellinator** [comment]
What creadits? It wasn't merged.
These embed drivers was based at https://github.com/DanielSant0s/Enceladus;
And will be replaced by a new method asap;

**Comment by Wolf3s** [comment]
> What creadits? It wasn't merged. These embed drivers was based at https://github.com/DanielSant0s/Enceladus; And will be replaced by a new method asap;

If you had use this pull to merge...

**Comment by Wellinator** [comment]
Okay. thx!

**Pull request closed without merging**
